openapi: 3.1.0
info: 
  title: Kafka gateway
  version: 0.0.1
paths:
  /access-token:
    post:
      tags:
        - authentication
      summary: Get the access token of the current oauth session
      description: Get the access token of the current oauth session... TODO
      operationId: access-token
      parameters:
        - name: decode
          in: query
          description: Whether to return the access token as decoded json value. Only supported in development.
          schema: 
            type: boolean
            default: false
      responses:
        '200':
          description: Got an access token
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                $ref: '#/components/schemas/Jwt'
        '401':
          description: Not logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomExceptionFormat'
        '403':
          description: Invalid csrf token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomExceptionFormat'
components:
  schemas:
    CustomExceptionFormat:
      type: object
      properties:
        timestamp:
          type: string
          example: 2026-03-18 15:00:00.00000
        statusCode:
          type: integer
          example: 200
        message:
          type: string
          example: OK
          description: Might be an empty string or null
        path:
          description: Relative path of the request which caused the error
          type: string
          example: /login
    Jwt:
      type: object
      description: See org.springframework.security.oauth2.jwt.Jwt

tags:
  - name: authentication
    description: Contains oauth session related endpoints